services:
  postgres:
    container_name: boilerplate_postgres
    image: postgres:18
    restart: unless-stopped
    env_file:
      - ./api/.env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - boilerplate_postgres_data:/var/lib/postgresql
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly:latest"
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
  api:
    container_name: boilerplate_api
    image: oven/bun:1.3.1
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
    working_dir: /app
    stop_signal: SIGINT
    stop_grace_period: 3s
    networks:
      - backend
    volumes:
      - .:/app
    command: "/bin/sh -c 'cd api && bun install && bun run --watch src/index.ts'"
  web:
    container_name: web
    image: oven/bun:1.3.1
    ports:
      - 5173:5173
    env_file:
      - ./web/.env
    working_dir: /app
    stop_signal: SIGINT
    stop_grace_period: 3s
    volumes:
      - .:/app
    command: "/bin/sh -c 'cd web && bun install && bun run dev'"

networks:
  backend:

volumes:
  boilerplate_postgres_data:
  dragonflydata:
